config/routes.rb
Fantasyhistory::Application.routes.draw do

  resources :posts do
    resources :comments
  end
  resources :rankings
  resources :teams
  resources :owners, :main
  resources :sports do
    resources :leagues
  end
  resources :leagues do
    resources :histories do
    end
  end
  root "welcome#index"

  post ':league/:league_id/histories/new' => 'histories#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :league
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :histories
  belongs_to :sport
  validates :name, presence: true, 
                   length: { minimum: 5 }
end

app/models/owner.rb
class Owner < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :leagues
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  http_basic_authenticate_with_name: name: "dhh", password: "secret", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
      
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destory

    redirect_to post_path(@post)
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  
  def new
    @history = History.new
    @league = League.find(params[:league_id])
  end

  def create
    @league = League.find(params[:league_id]) 
    @history = @league.histories.create(history_params)


    if @history.save
     redirect_to league_histories_path(@league)
    else
     render 'new' 
    end
  end

  def show
    @history = History.find(params[:id])

  end

  def import
    History.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  def index
    @league = League.find(params[:league_id])
    @histories = @league.histories.all


  end

  private
  def history_params
    params.require(:history).permit(:year, :team, :wins, :losses, :ties, :championship, :league_id)
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  
  def new
    @history = History.new
  end

  def create
    @history = History.new(params[:history].permit(:year, :team, :wins, :losses))
  end

  def import
    History.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def new
    @league = League.new
  end

  def show
    @league = League.find(params[:id])
    @sport = Sport.find(params[:id])
  end

  def index
    @leagues = League.all
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(params[:owner].permit(:name, :year, :wins, :losses, :title))
    @owner.save

    if @owner.save
      redirect_to @owner
    else
      render 'new'
    end
  end

  def show
    @owners = Owner.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :text))

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :text))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  def new
    @ranking = Ranking.new
  end

  def create
    @ranking = Ranking.new(params[:ranking].permit(:name, :number_of_teams))
    
    if @ranking.save
     redirect_to @ranking
    else
     render new 
    end
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def new
    @sport = Sport.new
  end

  def show
    @sport = Sport.find(params[:id]) 
    @league = League.all
  end

  def index
    @sports = Sport.all 
    @leagues = League.all
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def new
    @team = Team.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/comments/_comment.haml
%p 
  Commenter:
  = comment.commenter

%p
  Comment:
  = comment.body

%p
  = link_to 'Destroy Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }

app/views/comments/_form.haml
= form_for([@post, @post.comments.build]) do |f|
  %p
    = f.label :commenter
    = f.text_area :commenter
  %p
    = f.label :body
    = f.text_area :body

  %p
    = f.submit

app/views/histories/_form.haml
= form_for ([@league, @league.histories.new]) do |f|
  %p
    = f.label :year
  %p
    = f.text_area :year
  %p
    = f.label :team
  %p
    = f.text_area :team
  %p
    = f.label :wins
  %p
    = f.text_area :wins
  %p
    = f.label :losses
  %p
    = f.text_area :losses
  %p
    = f.label :ties
  %p
    = f.text_area :ties
  %p
    = f.label :championship
  %p
    = f.text_area :championship

  %p
    = f.submit

app/views/histories/index.haml
%h2.header Historical Rankings

%br

%button.years{ type: 'select' } Year 

%table.rankings
  %tr.headers
    %td Year
    %td Team
    %td Wins
    %td Losses
  - @league.histories.each do |history|
    %tr.history_row
      %td
        = history.year
      %td
        = history.team
      %td
        = history.wins
      %td
        = history.losses

%br

= link_to "New History", new_league_history_path
%br
= link_to "Back", league_path(@league)

app/views/histories/new.haml
%h2 Import History

= render 'form'

app/views/histories/show.haml
%h2 

%table
  = @histories 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'javascript' %>
  <%= render 'flashes' -%>
  <%= yield %>
</body>
</html>

app/views/leagues/show.haml
%h1 The People's League

= link_to "Complete History", league_histories_url(@league) 
= link_to "Back", sport_url(@sport)

app/views/owners/index.haml
%h2 Owner Table

%table
  %tr
    %th Owner
    %th Year
    %th Wins
    %th Losses

  - @owners.each do |owner| 
    %tr
      %td
        = owner.name
      %td
        = owner.year
      %td
        = owner.wins
      %td
        = owner.losses

app/views/owners/new.haml
%h1 People's League Historical Standings

%h3 Add New Result 

= form_for :owner, url: owners_path do |f|
  %p 
    = f.label :name
    = f.text_field :name
  %p
    = f.label :year
    = f.text_field :year
  %p
    = f.label :wins
    = f.text_field :wins
  %p
    = f.label :losses
    = f.text_field :losses

  %p
    = f.submit

app/views/owners/show.haml
%h2 New Owner Entry

%table
  %tr
    %th Owner
    %th Year
    %th Wins
    %th Losses

  - @owners.each do |owner| 
    %tr
      %td
        = owner.name
      %td
        = owner.year
      %td
        = owner.wins
      %td
        = owner.losses

app/views/posts/_form.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited
        this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br
      = f.text_field :title
  %p
    = f.label :text
    %br
      = f.text_area :text
  %p
    = f.submit

app/views/posts/edit.haml
%h1 Editing post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/index.haml
%h1 Listing posts
 
= link_to 'New Post', new_post_path

%table
  %tr
    %th Title
    %th Text
 
  - @posts.each do |post|
    %tr
      %td
        = post.title
      %td
        = post.text
      %td
        = link_to 'Show', post
      %td
        = link_to 'Edit', edit_post_path(post)
      %td
        = link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/new.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.haml
%p
  Title:
  = @post.title

 
%p
  Text:
  = @post.text

%h2 Comments
= render @post.comments


%h2 Add a Comment: 

= render "comments/form" 


= link_to 'Back', new_post_path

= link_to 'Show', post_path
= link_to 'Edit', edit_post_path(@post)

app/views/rankings/new.haml
%h2 Create a Rankings Table

= form_for :rankings, url: rankings_path do |f| 

  %p
    = f.label :name
    = f.text_area :name

app/views/sports/index.haml
%h2 These are the sports

%table
  - @sports.each do |sport|
    %tr
      %td
        = sport.name
      %td
        = link_to 'Show', sport

app/views/sports/new.haml
%h2 Create a new sport

app/views/sports/show.haml
%h1 
  = @sport.name
  
%h2 Leagues

%table
  - @sport.leagues.each do |league|
    %tr
      %td
        = league.name
      %td
        = link_to 'Show', league

= link_to 'Back', sports_path

app/views/welcome/index.haml
%h1 This is the main page.
= link_to "My Blog", controller: "posts"
= link_to "Sports", controller: "sports"